name: address_verify_example
description: Runnable example app for the address_verify package.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  address_verify:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
